snippets:
    home_post: '<div class="card post-item bg-transparent border-0 mb-5"><div class="card-body px-0"><h2 class="card-title"><a class="text-white opacity-75-onHover" href="/post/[[file]].html">[[title]]</a></h2><ul class="post-meta mt-3"><li class="d-inline-block mr-3"><span class="fas fa-clock text-primary"></span><a class="ml-1" href="#">[[date]]</a></li><li class="d-inline-block"><span class="fas fa-list-alt text-primary"></span><a class="ml-1" href="#">[[name]]</a></li></ul><p class="card-text my-4">[[body]]</p><a href="/post/[[file]].html" class="btn btn-primary">Read More</a></div></div>'

name: "default"
author: "devsimsek"
version: "v1.0"