name: Generate Site

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate content
        run: |
          python main.py gen
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git fetch
          git stash
          git merge '@{u}'
          git stash pop
          git add --all
          git commit -m "Add changes" -a
        shell: bash
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
